### ISSUE TITLE
Windows deployment guide is outdated/wrong

### ISSUE THREAD

**Issue by trondhindenes** [pivotal-cf/docs-ops-guide#28]
The "Diego for Windows" guide (https://docs.pivotal.io/pivotalcf/1-7/opsguide/deploying-diego.html) is wrong. It references downloads that are unavailable. The current version pf pcf seems to include a ops manager package - far different from what the doc outlines.

**Comment by awmartin** [comment]
@trondhindenes The documents you reference are for PCF 1.7, for which there are [Diego for Window installers](https://network.pivotal.io/products/elastic-runtime#/releases/4646). Later versions of PCF will not include Diego for Windows installers as it has entered End of Availability. PCF 1.9 is the last version for which they are available.

**Comment by trondhindenes** [comment]
Thanks @awmartin - I'm desperately googling around trying to find out how to actually deploy windows with pcf 1.10 and didn't notice that I ended up in an old documentation stub. 1.10 does _not_ contain any info on how to get Windows up and running (especially how to get hold of the Windows stemcell).

**Comment by awmartin** [comment]
@trondhindenes PCF Runtime for Windows 1.10 is scheduled for release in late March / early April.

**Comment by trondhindenes** [comment]
It's already released: https://network.pivotal.io/products/runtime-for-windows. Just seems that there's a massive need for updated docs.

**Comment by awmartin** [comment]
@trondhindenes It is already released for PCF 1.9, not 1.10.

**Comment by trondhindenes** [comment]
Ah. So i'm running ops manager 1.10, but with PCF Windows 1.9. Still, i'm struggling to find any documentation on how to get running with the PCF Runtime for Windows v.1.9. The v1.9 documentation simply says "Build your own vSphere stemcell". That's a problem as we're on aws only.

**Comment by awmartin** [comment]
The AWS stemcell release is targeted for early April. The current tile has only been released with vSphere stemcell instructions, but the tile can utilize the AWS stemcells when they become available.

**Comment by trondhindenes** [comment]
Thanks for the explanation. I realize we're well outside the original issue here, so I appreciate the clarification. Closing this issue.
