### ISSUE TITLE
Enabling volum services documentation incomplete

### ISSUE THREAD

**Issue by blinse** [pivotal-cf/docs-ops-guide#30]
We just enabled volume services on our elastic runtime v1.10.3-build.6 installation. The docs say 

"After completing these steps, developers can use the cf CLI to create service instances of the nfs service and bind them to their apps."

Yet when creating a volume service, a configuration object must be passed as argument. Otherwise the command `cf create-service nfs Existing` fails. 

Also the docs are unclear about whether the nfs service is part of the elastic runtime installation, or if a nfs server has to be set up by the user. In case it is part of the installation, the docs should say where to find the ip of the nfs server. 

This page (https://docs.cloudfoundry.org/devguide/services/using-vol-services.html) says that the command should be as follows: 

    cf create-service nfs Existing nfs_service_instance -c '{"share": "10.10.10.10/export/myshare"}'

Looking at the vms managed by bosh for the elastic runtime deployment, one can see an nfs_server vm. I guess this is the IP that we should be using for the create-service command.  But what is the mountpoint in PCF 1.10?

Also further configuration must be passed when binding a volume service to an app. Open source CF docs give this example: 

    cf bind-service my-app nfs_service_instance -c '{"uid":"1000","gid":"1000","mount":"/var/volume1"}'

This should also be explained in the PCF docs.

**Comment by bentarnoff** [comment]
Hey @blinse thanks for this. We've updated the "Enabling NFS Volume Services" topic to tell operators that they must have an NFS server running to enable NFS volume services. You can see the new note on our [staging site](https://docs-pcf-staging.cfapps.io/pivotalcf/1-10/opsguide/enable-vol-services.html).

We had some trouble parsing your other concerns. The "Enabling NFS Volume Services" topic links to [Using an External File System (Volume Services)](https://docs-pcf-staging.cfapps.io/pivotalcf/1-10/devguide/services/using-vol-services.html), which provides information about both the `cf create-service` and `cf bind-service`. 

Could you try rephrasing your desired changes to these topics? I'm also bringing in @rusha19, the PM of Volume Services, who can help address your concerns.

**Comment by blinse** [comment]
Hi @bentarnoff. Thanks for the quick reply, and for adjusting the docs so quickly. Thanks also for the link to the PCF docs for using volume services, I had overseen this. Will close this ticket.

**Comment by bentarnoff** [comment]
@blinse I'm not sure about the NFS server in your ERT deployment. Perhaps @rusha19 can help answer this question?
