### ISSUE TITLE
External User Management page for LDAP/SAML seems confusing and out of date

### ISSUE THREAD

**Issue by cdelashmutt-pivotal** [pivotal-cf/docs-ops-guide#33]
The doc page for adding users via LDAP/SAML some contradictory, and out of date for 1.10.

For instance, the note in step 1 says not to use the CF CLI, or UAAC, but in step 2 this note is immediately contradicted by the fact you are using the CF CLI and UAAC CLI.

Additionally, as of CF CLI v6.23.0 (1.10 Apps Manager has you download v6.26.0), we now have the ability to skip all the CF CLI + UAAC instructions in favor of a single CF CLI command the admin can execute.
## LDAP
`$ cf create-user j.smith@example.com --origin ldap`
## SAML
`$ cf create-user j.smith@example.com --origin <whatever-provider-name-you-set-in-ops-man>`

Then the admin can go about creating orgs, assigning rights to the new user, etc., before the user tries to sign in.

**Comment by ljarzynski** [comment]
Thanks @cdelashmutt-pivotal ! These updates sound like they would be very useful to our users. @scribblingfox, does the in-progress work for UAA include updating these instructions? cc @sreetummidi

**Comment by bentarnoff** [comment]
@sreetummidi Could you comment on this when you get a chance? Thanks.

**Comment by bentarnoff** [comment]
Hi @cdelashmutt-pivotal would you mind taking a look at the updated topic at http://docs-pcf-staging.cfapps.io/pivotalcf/1-10/opsguide/external-user-management.html? Please let us know if it addresses your concerns.

**Comment by bentarnoff** [comment]
Hey @cdelashmutt-pivotal I'm closing this issue now that we've updated the topic. Thanks for your help!
