### ISSUE TITLE
Steps missing in example for adding existing LDAP users.

### ISSUE THREAD

**Issue by haydonryan** [pivotal-cf/docs-ops-guide#36]
In the page [https://github.com/pivotal-cf/docs-ops-guide/blob/1.9/external-user-management.html.md.erb](https://github.com/pivotal-cf/docs-ops-guide/blob/1.9/external-user-management.html.md.erb) Step 2 of Step 2 states to do a curl to add existing Users to the CCDB, it doesn't show you how to get to the point where you can do that.

I'd change the text on step two to something like:
2. Taking the User's SAML or LDAP GUID from step 1, create a User record in the Cloud Controller Database using the USERS API.

```
cf target https://api.YOUR-SYSTEM-DOMAIN
cf login
export OAUTH-TOKEN=$(cf oauth-token|cut -d ' ' -f 2)

curl "https://api.YOUR-SYSTEM-DOMAIN/v2/users" -d '{
"guid": "YOUR-USER-GUID"
}' -X POST \
-H "Authorization: bearer $OAUTH-TOKEN" \
-H "Host: api.YOUR-SYSTEM-DOMAIN" \
-H "Content-Type: application/x-www-form-urlencoded" \
-H "Cookie: "
```

**Comment by haydonryan** [comment]
Version 1.7- current.

**Comment by ljarzynski** [comment]
Thanks for filing the issue @haydonryan, I'm working on updating the instructions.

**Comment by ljarzynski** [comment]
Would you mind explaining the export oauth part to me? Is that a necessity for these steps?

**Comment by haydonryan** [comment]
This saves manually copying in and pasting the large token.  It also saves you from having to manually edit the curl command to insert your token since I use an environment variable instead. :)

**Comment by ljarzynski** [comment]
Sorry for the delay. Picking this back up now as I just returned from vacay.

**Comment by ljarzynski** [comment]
Thanks @haydonryan ! Brought your suggested changes to all versions 1.7 to 1.11. See the master commit: https://github.com/pivotal-cf/docs-ops-guide/commit/2215c36b578bfff953a72c0d3fc9fcca317cffa4.
