### ISSUE TITLE
Item 4 vSphere link leads to Assure information. Link should lead to vSphere information.

### ISSUE THREAD

**Issue by gibbyn** [pivotal-cf/docs-ops-guide#41]
Item 4 vSphere link leads to Assure information. Link should lead to vSphere information.

**Comment by gibbyn** [comment]
Page URL:
https://docs.pivotal.io/pivotalcf/1-11/opsguide/ssl-term-haproxy.html

**Comment by animatedmax** [comment]
Hi @gibbyn The link should now lead to https://docs.pivotal.io/pivotalcf/1-11/customizing/config-er-vmware.html#networking

Thanks!
