### ISSUE TITLE
Outdated Scaling Recommendations

### ISSUE THREAD

**Issue by vchrisb** [pivotal-cf/docs-ops-guide#48]
The Scaling Recommendations Table is outdated and not complete.
https://docs.pivotal.io/pivotalcf/2-0/opsguide/scaling-ert-components.html

It misses following components:
* Filestorage
* Backup Prepare Node
* MySQL Monitor
* Cloud Controller Worker
* Syslog Adapter
* TCP Router
* Credhub

For Clock Global the recommended HA number is 2, while the default PAS 2.0 deployment sets this to 1.

**Comment by animatedmax** [comment]
Hi @vchrisb It looks like this issue has been taken care of. Thank you!
