### ISSUE TITLE
NFS Errand can be used to deploy a broker

### ISSUE THREAD

**Issue by ojhughes** [pivotal-cf/docs-ops-guide#49]
Hi

The page http://docs.pivotal.io/pivotalcf/1-12/opsguide/enable-vol-services.html says:

```
Note: You must have an NFS server running to enable NFS volume services. 
If you want to use NFS and do not currently have a server available, 
you can deploy the test NFS server bundled with the NFS Volume release.
```

There is actually an Errand that deploys an NFS broker - `NFS Broker Errand for Pivotal Elastic Runtime`. Running this Errand is probably the simplest solution when there isn't one already available (although doesn't let you configure the resources etc)

**Comment by kdolor-pivotal** [comment]
@ojhughes Thanks for submitting this issue. What does the broker not allow you to configure, as opposed to the NFS server?

**Comment by ojhughes** [comment]
Everything works as described but there is a 2nd option for creating an NFS Broker, enabling the errand via the ERT tile configuration.
