### ISSUE TITLE
Including Container Metrics in Syslog Drains links to staging docs

### ISSUE THREAD

**Issue by randomtask1155** [pivotal-cf/docs-ops-guide#57]
This link ref points to staging which results in a password prompt. 

https://github.com/pivotal-cf/docs-ops-guide/blob/ff2b00bb7097a60a8afeb04dcc744a5648318c95/logging-config-opsman.html.md.erb#L70

**Comment by animatedmax** [comment]
Hi @randomtask1155 
Thank you for bringing this to our attention. We have corrected this error and are in the process of auditing the rest of the documentation set to correct any other similar links.

https://docs.pivotal.io/pivotalcf/2-1/opsguide/logging-config-opsman.html
