### ISSUE TITLE
The docker registry proxy configuration is ambiguous about needing to be applied

### ISSUE THREAD

**Issue by ssherwood** [pivotal-cf/docs-ops-guide#60]
It appears that the change required to configure a proxy for a docker registry needs to be applied to become effective.  The docs are ambiguous: https://docs.pivotal.io/pivotalcf/1-12/opsguide/docker-registry.html#proxy

I think that this section could be more clear about how/why this change needs to be applied because it isn't entirely obvious.

**Comment by pspinrad** [comment]
Thanks @ssherwood -- see https://github.com/pivotal-cf/docs-ops-guide/commit/c236cd5d63c1379a29c534ce1daceee9dbcc21cc for change staged to publish with next build.
