### ISSUE TITLE
Securing Services Instance Credentials with Runtime CredHub will NOT work unless the resource count for credhub is > 0

### ISSUE THREAD

**Issue by matthewfischer** [pivotal-cf/docs-ops-guide#62]
By default the instance count for credhub is 0. If you enable Secure Service Credentials without raising this number to at least 1, the service tiles will fail to install (like MySQL and RabbitMQ). They will fail because they will unable to resolve the bosh-dns record for credhub (since it does not exist). I think at least a Note or Warning here that says "if you enable this you need to change the resource config" is merited.

**Comment by pspinrad** [comment]
Thanks @matthewfischer -- added the info https://github.com/pivotal-cf/docs-ops-guide/commit/10d47dbe74d5aaeaac9067be5a3eb4100a4607ae
