### ISSUE TITLE
Zendesk reference link is broken on this page - PCF 2.3

### ISSUE THREAD

**Issue by parth-pandit** [pivotal-cf/docs-ops-guide#77]
This is for **PCF 2.3** topic **Configure LDAP as an Identity Provider for PAS**. There is a reference link provided on how to configure LDAP as mentioned below, which is broken. It has to be updated.

https://discuss.zendesk.com/hc/en-us/articles/204140418-Configuring-LDAP-Integration-with-Pivotal-Cloud-Foundry-

**Comment by ljarzynski** [comment]
Thanks @parth-pandit ! Looks like one of our writers pushed a fix for this: https://github.com/pivotal-cf/docs-ops-guide/commit/d3610b69996e9d490d3c1786146a179a9392c5fc

Thanks @animatedmax !!
