### ISSUE TITLE
Enable TCP Routing clarity on IaaS changes

### ISSUE THREAD

**Issue by edbyford** [pivotal-cf/docs-ops-guide#96]
@dlresende and I were running through acceptance to Enable TCP routing.

We found the steps on this page https://docs.pivotal.io/pivotalcf/2-6/opsguide/tcp-routing-ert-config.html to be quite difficult to follow. We would suggest: 

1. Mention method of updating (cf cli vs GUI) at the start of the instructions. This will then affect the following steps
1. Generic steps are mixed with IaaS specific steps, which makes understanding a bit confusing. Maybe well separating what's generic from what's IaaS specific would help, e.g.

- Generic step description
  - **AWS/GCP**: Do this
  - **vSphere**: Do this

- Second generic step description
  - **AWS**: do this
  - **GCP**: do that
  - **vSphere**: do the other

**Comment by cshollingsworth** [comment]
Thanks, @edbyford ! We've edited the procedure for clarity, and the changes should appear on the docs site soon.
