### ISSUE TITLE
Github link wrong

### ISSUE THREAD

**Issue by skibum55** [pivotal-cf/docs-ops-guide#99]
Just went to create a PR to update a page and it took me to the wrong github repo - http://github.com/pivotal-cf/docs-operating-pas/tree/2.7/external-user-management.html.md.erb.  Please update to use this repo.  Thanks

**Comment by mjgutermuth** [comment]
Hi @skibum55! Thanks for reporting this. Which page were you on when you clicked the link?

**Comment by animatedmax** [comment]
Hi @skibum55 
We rebuild the page links back in November and, based on our tests, the issue seems to have been resolved. If you come across this again or another issue, please let us know. Thanks!
